name: audiorecorder
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.8
  get_it: ^7.2.0
  intl: ^0.17.0
  path: 1.8.0
  path_provider: ^2.0.8
  permission_handler: ^8.3.0
  provider: ^6.0.1
  record: ^3.0.2
  just_audio: ^0.9.18
  logger: ^1.1.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
